name = "Nvim"

[[config]]
src = "init.lua"
dst = {"Windows" = "%LocalAppData%\\nvim\\init.lua", "Darwin"= "~/.config/nvim/init.lua", "*" = "~/.config/nvim/init.lua"}

[[install]]
name = {"Windows" = "neovim", "Darwin"= "neovim", "*" = "nvim --classic"}
cmd = "nvim"
manager = {"Windows" = "scoop", "Darwin"= "brew", "Linux" = "snap"}
