name = "Nvim"

[[config]]
src = "init.lua"
dst = "~/.config/nvim/init.lua"

[[install]]
name = {"Windows" = "neovim", "Darwin"= "neovim", "*" = "nvim --classic"}
cmd = "nvim"
manager = {"Windows" = "scoop", "Darwin"= "brew", "Linux" = "snap"}
