[[config]]
name = "bat"
src = "bat.conf"
dst = "bat --config-file"
skip = {"Linux" = true, "*" = false}  # Skip Linux

[[config]]
name = "bat for Linux"
src = "ln -sf /usr/bin/batcat ~/.local/bin/bat; echo 'bat.conf'"
dst = "batcat --config-file"
skip = {"Linux" = false, "*" = true}  # Only Linux

[[install]]
name = "bat"
command = {"Linux" = "batcat", "*" = "bat"}
