###############################
# Utility functions for zshrc #
###############################
_echo() {  # Print message with different types
    local UNDERLINE=$'\e[4m'
    local DIM=$'\e[2m'
    local RESET=$'\e[0m'

    local type="$1"
    shift
    local message="$@"

    case "$type" in
        --err)
            echo -e "${DIM}[${RESET}${UNDERLINE}Error${RESET}${DIM}]${RESET} $message" >&2
            ;;
        --warn)
            echo -e "${DIM}[${RESET}Warning${DIM}]${RESET} $message"
            ;;
        --info)
            echo -e "${DIM}[Info]${RESET} $message"
            ;;
        --debug)
            echo -e "[Debug] $message"
            ;;
        --title)
            echo ""
            if [[ "$(locale charmap 2>/dev/null)" == "UTF-8" ]]; then
                local horizontal_bar=$(printf '═%.0s' {1..${#message}})
                local vertical_bar="║"
                local top_left="╔═"
                local top_right="═╗"
                local bottom_left="╚═"
                local bottom_right="═╝"
            else
                local horizontal_bar=$(printf '=%.0s' {1..${#message}})
                local vertical_bar="|"
                local top_left="+="
                local top_right="=+"
                local bottom_left="+="
                local bottom_right="=+"
            fi
            echo -e "${DIM}${top_left}${horizontal_bar}${top_right}${RESET}"
            echo -e "${DIM}${vertical_bar}${RESET} $message ${DIM}${vertical_bar}${RESET}"
            echo -e "${DIM}${bottom_left}${horizontal_bar}${bottom_right}${RESET}"
            ;;
        --command)
            echo -e "${DIM}\$${RESET} ${UNDERLINE}$message${RESET}"
            ;;
        *)
            echo "$type $message"
            ;;
    esac
}

_verbose_run() {  # Print command before running it
    _echo --command "$1"
    eval "$1"
}

_has_cmd() {  # Check if command exists
    # Usage:
    #    _has_cmd 'cmd'  # Check if cmd exists
    #    _has_cmd -v/--verbose 'cmd'  # Check if cmd exists, and print error message if not exists
    local verbose=0
    if [[ "$1" == '-v' || "$1" == '--verbose' ]]; then
        verbose=1
        shift
    fi
    if command -v "$@" > /dev/null 2>&1; then  # Command exists
        return 0
    else  # Command not exists
        [[ "$verbose" == 1 ]] && _echo --err "Command not found: $1"
        return 1
    fi
}


#################
# Package Inits #
#################
# ZSH Init
export ZSH="$HOME/.oh-my-zsh"  # Path to your oh-my-zsh installation.
ZSH_THEME="powerlevel10k/powerlevel10k"  # See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
DISABLE_UNTRACKED_FILES_DIRTY="true"  # Disable the dirty prompt when in a repository with many untracked files.
DISABLE_AUTO_UPDATE="true"  # Disable bi-weekly auto-update checks.
HIST_STAMPS="yyyy-mm-dd"  # History timestamp format. "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
plugins=(
    colored-man-pages  # man page colorized
    zsh-autosuggestions  # 3rd party plugins. gray suggestions in tail
    zsh-syntax-highlighting  # 3rd party plugins. highlights shell commands
)
case $(uname -a) in  # this problem only on Windows Subsystem Linux
    *Microsoft*)
        unsetopt BG_NICE  # for "z", to avoid _z_precmd:1: nice(5) failed: operation not permitted
        export LS_COLORS="${LS_COLORS}ow=34;36:"  # change windows directory bg color.
        ;;
    *Darwin*)
        eval $(/opt/homebrew/bin/brew shellenv)
        ;;
esac

source $ZSH/oh-my-zsh.sh  # Alias after this line to avoid being overridden by oh-my-zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Python User Site-Package Binaries
if _has_cmd python3; then
    export PATH="$(python3 -m site --user-base)/bin:$PATH"
fi

# Init Zoxide (z and zi)
if _has_cmd zoxide; then
    eval "$(zoxide init zsh)"
fi

# Init Eza (ls and tree)
if _has_cmd eza; then
    alias ls='eza --icons=auto --group-directories-first -h'
    alias tree='eza --icons=auto --group-directories-first -h -T'
fi

# Init Yazi (yz)
if _has_cmd yazi; then
    function yz() {
        local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
        trap "rm -f -- '$tmp'" INT TERM EXIT
        command yazi "$@" --cwd-file="$tmp"
        IFS= read -r -d '' cwd < "$tmp"
        [ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
        rm -f -- "$tmp"
    }
fi

# Init Bun (bun)
if _has_cmd bun; then
    export PATH="$HOME/.bun/bin:$PATH"
fi

# Set EDITOR and VISUAL to nvim
if _has_cmd nvim; then
    export EDITOR='nvim'
    export VISUAL='nvim'
fi



####################
# Update Functions #
####################
up() {  # Update package managers information and upgrade packages.
    # The term `update` means to get the latest package information from remote servers.
    # The term `upgrade` means to actually install the latest versions of the packages.
    up_pipx() {
        _echo --title 'Pipx Update & Upgrades'
        _has_cmd --verbose 'pipx' || return 1  # If pipx not installed, return False
        _verbose_run "pipx upgrade-all"  # 20s
    }
    up_pip() {
        _echo --title 'Upgrade pip'
        _has_cmd --verbose 'python3' || return 1  # If python3 not installed, return False
        _verbose_run "python3 -m pip install --upgrade pip"
    }
    up_brew() {
        if [[ "$(uname -s)" == "Darwin" ]]; then  # Only work on macOS
            _echo --title 'Brew Update & Upgrades'
            _has_cmd --verbose 'brew' || return 1  # If brew not installed, return False
            _verbose_run 'brew update'
            _verbose_run 'brew upgrade --greedy --yes'
            _verbose_run 'brew list --cask | xargs brew upgrade --cask'
            _verbose_run 'brew autoremove'
            _verbose_run 'brew cleanup --prune=all'
        fi
    }
    up_apt() {
        if [[ "$(uname -s)" == "Linux" ]]; then  # Only work on Linux
            _echo --title 'Apt Update & Upgrades'
            _has_cmd --verbose 'apt' || return 1  # If apt not installed, return False
            _verbose_run 'sudo apt update'
            _verbose_run 'sudo apt dist-upgrade -y'
            _verbose_run 'sudo apt autoremove -y'
        fi
    }
    up_snap() {
        if [[ "$(uname -s)" == "Linux" ]]; then  # Only work on Linux
            _echo --title 'Snap Update & Upgrades'
            _has_cmd --verbose 'snap' || return 1  # If snap not installed, return False
            _verbose_run 'sudo snap refresh'
        fi
    }
    up_npm() {
        _echo --title 'NPM Update & Upgrades'
        _has_cmd --verbose 'npm' || return 1  # If npm not installed, return False
        _verbose_run 'npm update --global'
    }
    up_bun() {
        _echo --title 'Bun Update & Upgrades'
        _has_cmd --verbose 'bun' || return 1  # If bun not installed, return False
        _verbose_run 'bun update --global'
    }
    up_omz() {
        _echo --title 'Upgrade Oh-My-Zsh'
        _has_cmd --verbose 'omz' || return 1  # If omz not installed, return False
        _verbose_run 'omz update'
    }
    up_rust() {
        _echo --title 'Upgrade Rust'
        _has_cmd --verbose 'rustup' || return 1  # If rustup not installed, return False
        _verbose_run 'rustup update'
    }
    up_python() {
        _echo --title 'Upgrade Python'
        _has_cmd --verbose 'brew' || return 1  # If brew not installed, return False
        # _verbose_run 'brew upgrade python3'
        _verbose_run 'open "$(brew --prefix python3)/Python Launcher 3.app"'
    }
    local package_managers=('pipx' 'brew' 'apt' 'snap' 'npm' 'bun')  # Available package managers to update and upgrade
    local packages=('omz' 'rust' 'python')  # All available packages for upgrade
    local daily_upgrades=('brew' 'apt' 'snap' 'pipx' 'npm' 'bun')  # Available packages for daily upgrade
    if [[ $# -eq 0 ]]; then  # Run `up` to run daily updates and upgrades
        for pm in "${daily_upgrades[@]}"; do  # Selected packages will be upgraded daily
            eval "up_$pm"
        done
    else  # Run `up pip brew` for brew and pip upgrades only.
        for arg in "$@"; do
            if [[ " ${package_managers[*]} " =~ " $arg " ]]; then  # $arg is a package manager
                eval "up_$arg"
            elif [[ " ${packages[*]} " =~ " $arg " ]]; then  # $arg is a package
                eval "up_$arg"
            else
                echo "[Error] Unknown package or package manager: $arg"
                echo "[Info] Supported : ${package_managers[*]} ${packages[*]}"
            fi
        done
    fi
}


#################################
# Virtual Environment Functions #
#################################
venv() {  # Deactivate if in a venv, or activate .venv/bin/activate
    local requirements=('requirements.txt' 'requirements-dev.txt' 'requirements-opt.txt')
    # If venv is activated, deactivate it.
    if [[ -n "$VIRTUAL_ENV" ]]; then
        _verbose_run "deactivate"
        return
    fi
    # check uv command
    _has_cmd --verbose 'uv' || return 1
    # If .venv/ not exists, create venv and relaunch the function.
    if [[ ! -d "./.venv" ]]; then
        _verbose_run "uv venv"  # create venv
        venv
        return
    fi
    # If .venv/ exists, but not executable, recreate venv and relaunch the function.
    if [[ ! -x "./.venv/bin/python" ]]; then
        _verbose_run "rm -r ./.venv"  # remove venv
        venv
        return
    fi
    # If .venv/ exists, but version is old, recreate the.venv/
    if ! ./.venv/bin/python --version &> /dev/null; then
        _verbose_run "rm -r ./.venv"  # remove venv
        venv
        return
    fi
    # If .venv/ exists, and python is executable, update it and activate
    for file in ${requirements[@]}; do
        if [[ -f "./$file" ]]; then
            _verbose_run "uv pip install --refresh -r ./$file"
        fi
    done
    # Activate the venv
    _verbose_run "source ./.venv/bin/activate"
}

venvx() {  # Activate venv if needed, run a .py script, then deactivate if venv was activated here.
    local py_scripts=()
    for f in *.py; do
        if [[ -f "$f" ]]; then
            py_scripts+=("$f")
        fi
    done
    if [[ ${#py_scripts[@]} -eq 0 ]]; then
        _echo --warn "No Python scripts detected"
        return 1
    fi
    local script
    if [[ ${#py_scripts[@]} -eq 1 ]]; then
        script="${py_scripts[*]}"
    elif _has_cmd fzf; then
        script=$(printf '%s\n' "${py_scripts[@]}" | fzf --preview 'bat --color=always --line-range=:100 {}' --preview-window up)
    else
        select script in "${py_scripts[@]}"; do
            break
        done
    fi
    if [[ -z "$script" ]]; then
        _echo --err "No Script Selected"
        return 1
    fi
    local prev_venv="$VIRTUAL_ENV"
    if [[ -z "$prev_venv" ]]; then
        _echo --title "Activating Venv"
        venv
    fi
    _echo --title "Running Script"
    _verbose_run "python \"$script\""
    if [[ -z "$prev_venv" ]]; then
        _echo --title "Deactivating Venv"
        venv
    fi
}


###################
# Proxy Functions #
###################
proxy() {  # proxy [on|off|status]
    local proxy_address="127.0.0.1:1088"
    local proxy_protocol="http"  # "socks5"
    local proxy_envvars=("http_proxy" "https_proxy" "all_proxy" "HTTP_PROXY" "HTTPS_PROXY" "ALL_PROXY")

    if [[ $# -eq 0 ]]; then
        for envvar in "${proxy_envvars[@]}"; do
            if [[ -n "$(eval echo \$${envvar})" ]]; then  # if $http_proxy is non-empty
                _verbose_run "proxy off"
                return
            fi
        done
        _verbose_run "proxy on"
        return
    fi

    for arg in "$@"; do
        case "$arg" in
            on)
                for envvar in "${proxy_envvars[@]}"; do
                    if [[ -z "$(eval echo \$${envvar})" ]]; then  # if $http_proxy is zero-length
                        _verbose_run "export $envvar=${proxy_protocol}://$proxy_address"
                    fi
                done
                ;;
            off)
                for envvar in "${proxy_envvars[@]}"; do
                    _verbose_run "unset $envvar"
                done
                ;;
            status)
                for envvar in "${proxy_envvars[@]}"; do
                    if [[ -n "$(eval echo \$${envvar})" ]]; then
                        _echo --info "$envvar: $(eval echo \$${envvar})"
                    fi
                done
                ;;
            *)
                _echo --err "Unknown argument: $arg"
                _echo --info "Usage: proxy [on|off|status]"
                ;;
        esac
    done
}
